/*
Navicat MySQL Data Transfer

Source Server         : 127.0.0.1
Source Server Version : 50725
Source Host           : 10.80.6.10:8090
Source Database       : selfservice

Target Server Type    : MYSQL
Target Server Version : 50725
File Encoding         : 65001

Date: 2022-01-18 14:41:48
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for ss_processconfig
-- ----------------------------
DROP TABLE IF EXISTS `ss_processconfig`;
CREATE TABLE `ss_processconfig` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ss_pc_dictype` varchar(50) DEFAULT NULL,
  `ss_pc_diccode` varchar(50) DEFAULT NULL,
  `ss_pc_dicdesc` varchar(50) DEFAULT NULL,
  `ss_pc_demo` varchar(2000) DEFAULT NULL,
  `ss_pc_createdate` datetime(6) DEFAULT NULL,
  `ss_pc_creator` varchar(50) DEFAULT NULL,
  `ss_pc_update` datetime(6) DEFAULT NULL,
  `ss_pc_upuser` varchar(10) DEFAULT NULL,
  `ss_pc_processcode` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ss_processconfig_ss_pc_diccode_f03fab4c` (`ss_pc_diccode`),
  KEY `ss_processconfig_ss_pc_dictype_08e9d6a5` (`ss_pc_dictype`),
  KEY `ss_processconfig_ss_pc_processcode_af5637fc` (`ss_pc_processcode`)
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of ss_processconfig
-- ----------------------------
INSERT INTO `ss_processconfig` VALUES ('3', 'Business', 'ORDR', '预约', '{\"1\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card12.gif\",\"cardmode\":\"12\"}},\"2\":{\"desc\":\"流调表\",\"code\":\"srvylist\",\"page\":\"/WebAPP/pages/common/srvylist.html?\",\"config\":\"\"},\"3\":{\"desc\":\"选择一级科室\",\"code\":\"level1dep\",\"page\":\"/WebAPP/pages/prereg/level1department.html?\",\"config\":\"\"},\"4\":{\"desc\":\"选择二级科室\",\"code\":\"level2dep\",\"page\":\"/WebAPP/pages/prereg/department.html?\",\"config\":\"\"},\"5\":{\"desc\":\"选择医生\",\"code\":\"predoc\",\"page\":\"/WebAPP/pages/prereg/doctor.html?\",\"config\":\"\"},\"6\":{\"desc\":\"选择日期\",\"code\":\"predocdat\",\"page\":\"/WebAPP/pages/prereg/doctordetails.html?\",\"config\":\"\"},\"7\":{\"desc\":\"选择时间\",\"code\":\"predoctime\",\"page\":\"/WebAPP/pages/prereg/doctor.timeinfo.html?\",\"config\":\"\"},\"8\":{\"desc\":\"确认联系方式\",\"code\":\"modifypat\",\"page\":\"/WebAPP/pages/common/modifypatinfo.html?\",\"config\":\"\"},\"9\":{\"desc\":\"确认完成\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?\",\"config\":\"\"}}', '2021-08-09 22:23:46.000000', null, null, null, 'ORDR');
INSERT INTO `ss_processconfig` VALUES ('4', 'Business', 'OBTNO', '取号', '{\"1\":{\"desc\":\"选择患者类型\",\"code\":\"pattype\",\"page\":\"/WebAPP/pages/common/readcard.html\",\"config\":\"\"},\"2\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":{\"url\":\"\",\"cardmode\":\"\"}},\"3\":{\"desc\":\"选择医保类别\",\"code\":\"insutype\",\"page\":\"/WebAPP/pages/insu/pattype.html?\",\"config\":\"\"},\"4\":{\"desc\":\"选择慢病类型\",\"code\":\"diag\",\"page\":\"/WebAPP/pages/insu/diag.html?\",\"config\":\"\"},\"5\":{\"desc\":\"选择预约记录\",\"code\":\"getpredetails\",\"page\":\"/WebAPP/pages/prereg/predetails.html?AllowReund=GET\",\"config\":\"\"},\"6\":{\"desc\":\"挂号信息\",\"code\":\"showreg\",\"page\":\"/WebAPP/pages/prereg/show.html?\",\"config\":\"\"},\"7\":{\"desc\":\"选择支付方式\",\"code\":\"paymode\",\"page\":\"/WebAPP/pages/common/paymode.html?\",\"config\":\"\"},\"8\":{\"desc\":\"扫码\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?\",\"config\":\"\"}}', null, null, null, null, 'OBTNO');
INSERT INTO `ss_processconfig` VALUES ('5', 'Business', 'CANCORDR', '取消预约', '{\"1\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card12.gif\",\"cardmode\":\"12\"}},\"2\":{\"desc\":\"选择预约记录\",\"code\":\"getpredetails\",\"page\":\"/WebAPP/pages/prereg/predetails.html?AllowReund=Y\",\"config\":\"\"}}', null, null, null, null, 'CANCORDR');
INSERT INTO `ss_processconfig` VALUES ('6', 'Business', 'QURY', '查询', '{\"1\":{\"desc\":\"查询\",\"code\":\"query\",\"page\":\"/WebAPP/pages/query/menu.html?\",\"config\":{}}}', null, null, null, null, 'QURY');
INSERT INTO `ss_processconfig` VALUES ('7', 'Business', 'CERTPRT', '凭条打印', '{\"1\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card123.gif\",\"cardmode\":\"123\"}},\"2\":{\"desc\":\"打印\",\"code\":\"printmain\",\"page\":\"/WebAPP/pages/print/cert.html?\",\"config\":\"\"}}', null, null, null, null, 'CERTPRT');
INSERT INTO `ss_processconfig` VALUES ('8', 'Business', 'DRINCRNO', '加号', '{\"1\":{\"desc\":\"选择患者类型\",\"code\":\"pattype\",\"page\":\"/WebAPP/pages/common/readcard.html?\",\"config\":\"\\\"\\\\\\\"{}\\\\\\\"\\\"\"},\"2\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":\"\\\"\\\\\\\"{\\\\\\\\\\\\\\\"url\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"cardmode\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"}\\\\\\\"\\\"\"},\"3\":{\"desc\":\"选择医保类型\",\"code\":\"insutype\",\"page\":\"/WebAPP/pages/insu/pattype.html?\",\"config\":\"\"},\"4\":{\"desc\":\"选择慢病诊断\",\"code\":\"diag\",\"page\":\"/WebAPP/pages/insu/diag.html?\",\"config\":\"\"},\"5\":{\"desc\":\"输入加号码\",\"code\":\"input\",\"page\":\"/WebAPP/pages/common/text.input.html?\",\"config\":\"\"},\"6\":{\"desc\":\"预约记录查询\",\"code\":\"getpredetails\",\"page\":\"/WebAPP/pages/prereg/predetails.html?AllowReund=GET\",\"config\":\"\"},\"7\":{\"desc\":\"挂号信息\",\"code\":\"showreg\",\"page\":\"/WebAPP/pages/prereg/show.html?\",\"config\":\"\"},\"8\":{\"desc\":\"支付方式\",\"code\":\"paymode\",\"page\":\"/WebAPP/pages/common/paymode.html?\",\"config\":\"\"},\"9\":{\"desc\":\"支付\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?\",\"config\":\"\"}}', null, null, null, null, 'DRINCRNO');
INSERT INTO `ss_processconfig` VALUES ('9', 'Business', 'Charge', '门诊缴费', '{\"1\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card123.gif\",\"cardmode\":\"123\"}},\"2\":{\"desc\":\"查询待缴费结算单\",\"code\":\"PayingList\",\"page\":\"/WebAPP/pages/charge/orderlist.html?\",\"config\":\"\"},\"3\":{\"desc\":\"确认信息\",\"code\":\"chargeshow\",\"page\":\"/WebAPP/pages/charge/divide.show.html?\",\"config\":\"\"},\"4\":{\"desc\":\"支付方式选择\",\"code\":\"paymode\",\"page\":\"/WebAPP/pages/common/paymode.html?\",\"config\":\"\"},\"5\":{\"desc\":\"支付\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?\",\"config\":\"\"}}', null, null, null, null, 'Charge');
INSERT INTO `ss_processconfig` VALUES ('10', 'Business', 'Reg', '挂号', '{\"1\":{\"desc\":\"选择患者类型\",\"code\":\"pattype\",\"page\":\"/WebAPP/pages/common/readcard.html?\",\"config\":\"\"},\"2\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":\"{\\\"url\\\":\\\"\\\",\\\"cardmode\\\":\\\"\\\"}\"},\"3\":{\"desc\":\"选择医保类别\",\"code\":\"insutype\",\"page\":\"/WebAPP/pages/insu/pattype.html?\",\"config\":\"\"},\"4\":{\"desc\":\"选择慢病类型\",\"code\":\"diag\",\"page\":\"/WebAPP/pages/insu/diag.html?\",\"config\":\"\"},\"5\":{\"desc\":\"选择一级科室\",\"code\":\"level1dep\",\"page\":\"/WebAPP/pages/prereg/level1department.html?\",\"config\":\"\"},\"6\":{\"desc\":\"选择二级科室\",\"code\":\"level2dep\",\"page\":\"/WebAPP/pages/prereg/department.html?\",\"config\":\"\"},\"7\":{\"desc\":\"选择医生\",\"code\":\"predoc\",\"page\":\"/WebAPP/pages/prereg/doctor.html?\",\"config\":\"\"},\"8\":{\"desc\":\"挂号信息\",\"code\":\"showreg\",\"page\":\"/WebAPP/pages/prereg/show.html?\",\"config\":\"\"},\"9\":{\"desc\":\"支付方式选择\",\"code\":\"paymode\",\"page\":\"/WebAPP/pages/common/paymode.html?\",\"config\":\"\"},\"10\":{\"desc\":\"支付\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?\",\"config\":\"\"}}', null, null, null, null, 'Reg');
INSERT INTO `ss_processconfig` VALUES ('11', 'Business', 'HLTJ', '健康天津', '{\"1\":{\"desc\":\"健康天津\",\"code\":\"jktj\",\"page\":\"/WebAPP/pages/selfdef.health.tianjin.html?\",\"config\":{}}}', null, null, null, null, 'HLTJ');
INSERT INTO `ss_processconfig` VALUES ('12', 'Business', 'PreOrder', '预约记录查询', '{\"1\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card12.gif\",\"cardmode\":\"12\"}},\"2\":{\"desc\":\"选择预约记录\",\"code\":\"getpredetails\",\"page\":\"/WebAPP/pages/prereg/predetails.html?AllowReund=N\",\"config\":\"\"}}', null, null, null, null, 'PreOrder');
INSERT INTO `ss_processconfig` VALUES ('13', 'Business', 'ChargeDetail', '缴费记录查询', '{\"1\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card12.gif\",\"cardmode\":\"12\"}},\"2\":{\"desc\":\"缴费明细\",\"code\":\"getpredetails\",\"page\":\"/WebAPP/pages/query/opinv.html?\",\"config\":\"\"}}', null, null, null, null, 'ChargeDetail');
INSERT INTO `ss_processconfig` VALUES ('14', 'Business', 'ItmPrice', '收费项价格查询', '{\"1\":{\"desc\":\"输入\",\"code\":\"textinput\",\"page\":\"/WebAPP/pages/common/text.input.html?KeyType=letter\",\"config\":{}},\"2\":{\"desc\":\"查询\",\"code\":\"getpredetails\",\"page\":\"/WebAPP/pages/query/itemprice.html?\",\"config\":\"\"}}', null, null, null, null, 'ItmPrice');
INSERT INTO `ss_processconfig` VALUES ('15', 'Business', 'UnionOP', '联合门诊菜单', '{\"1\":{\"desc\":\"联合门诊\",\"code\":\"unionmenu\",\"page\":\"/WebAPP/pages/prereg/union.menu.html?\",\"config\":{}}}', null, null, null, null, 'UnionOP');
INSERT INTO `ss_processconfig` VALUES ('16', 'Business', 'NAReg', '核酸挂号菜单', '{\"1\":{\"desc\":\"核酸挂号\",\"code\":\"naregmenu\",\"page\":\"/WebAPP/pages/prereg/nareg.menu.html?\",\"config\":{}}}', null, null, null, null, 'NAReg');
INSERT INTO `ss_processconfig` VALUES ('17', 'Business', 'MedPrice', '收费项价格查询', '{\"1\":{\"desc\":\"输入\",\"code\":\"textinput\",\"page\":\"/WebAPP/pages/common/text.input.html?KeyType=letter\",\"config\":{}},\"2\":{\"desc\":\"查询\",\"code\":\"queryprice\",\"page\":\"/WebAPP/pages/query/itemprice.html?\",\"config\":\"\"}}', null, null, null, null, 'MedPrice');
INSERT INTO `ss_processconfig` VALUES ('18', 'Business', 'AddDeposit', '住院交押金', '{\"1\":{\"desc\":\"选择患者类型\",\"code\":\"pattype\",\"page\":\"/WebAPP/pages/common/readcard.html?\",\"config\":{}},\"2\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":\"\"},\"3\":{\"desc\":\"查询就诊记录\",\"BusinessType\":\"Charge\",\"code\":\"AdmList\",\"page\":\"/WebAPP/pages/charge/admlist.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card1.png\",\"cardmode\":\"1\"}},\"4\":{\"desc\":\"输入金额\",\"code\":\"input\",\"page\":\"/WebAPP/pages/common/text.input.html?\",\"config\":\"\"},\"5\":{\"desc\":\"支付方式选择\",\"code\":\"paymode\",\"page\":\"/WebAPP/pages/common/paymode.html?\",\"config\":\"\"},\"6\":{\"desc\":\"支付\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?paytype=Charge\",\"config\":\"\"}}', null, null, null, null, 'AddDeposit');
INSERT INTO `ss_processconfig` VALUES ('19', 'Business', 'ORDR', '联合门诊预约', '{\"1\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card12.gif\",\"cardmode\":\"12\"}},\"2\":{\"desc\":\"流调表\",\"code\":\"srvylist\",\"page\":\"/WebAPP/pages/common/srvylist.html?\",\"config\":\"\"},\"3\":{\"desc\":\"提示\",\"code\":\"tips\",\"page\":\"/WebAPP/pages/prereg/union.tips.html?\",\"config\":\"\"},\"4\":{\"desc\":\"选择一级科室\",\"code\":\"level1dep\",\"page\":\"/WebAPP/pages/prereg/level1department.html?\",\"config\":\"\"},\"5\":{\"desc\":\"选择二级科室\",\"code\":\"level2dep\",\"page\":\"/WebAPP/pages/prereg/department.html?\",\"config\":\"\"},\"6\":{\"desc\":\"选择医生\",\"code\":\"predoc\",\"page\":\"/WebAPP/pages/prereg/doctor.html?\",\"config\":\"\"},\"7\":{\"desc\":\"选择日期\",\"code\":\"predocdat\",\"page\":\"/WebAPP/pages/prereg/doctordetails.html?\",\"config\":\"\"},\"8\":{\"desc\":\"选择时间\",\"code\":\"predoctime\",\"page\":\"/WebAPP/pages/prereg/doctor.timeinfo.html?\",\"config\":\"\"},\"9\":{\"desc\":\"确认联系方式\",\"code\":\"modifypat\",\"page\":\"/WebAPP/pages/common/modifypatinfo.html?\",\"config\":\"\"},\"10\":{\"desc\":\"确认完成\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?\",\"config\":\"\"}}', '2021-08-09 22:23:46.000000', null, null, null, 'UnionOP-ORDR');
INSERT INTO `ss_processconfig` VALUES ('20', 'Menu', 'NAReg', '核酸检测', '{\"1\":{\"desc\":\"核酸检测号\",\"processcode\":\"NAReg-Reg\",\"icons\":\"\"},\"2\":{\"desc\":\"取号\",\"processcode\":\"NAReg-OBTNO\",\"icons\":\"\"},\"3\":{\"desc\":\"缴费\",\"processcode\":\"Charge\",\"icons\":\"\"},\"4\":{\"desc\":\"凭条打印\",\"processcode\":\"CERTPRT\",\"icons\":\"\"}}', '2021-08-09 22:23:46.000000', null, null, null, '');
INSERT INTO `ss_processconfig` VALUES ('21', 'Menu', 'EIP', '电子发票打印机', '{\"1\":{\"desc\":\"电子票据\",\"processcode\":\"EIP\",\"icons\":\"\"},\"2\":{\"desc\":\"电子清单\",\"processcode\":\"ED\",\"icons\":\"\"}}', '2021-08-09 22:23:46.000000', null, null, null, '');
INSERT INTO `ss_processconfig` VALUES ('22', 'Business', 'EIP', '电子发票', '{\"1\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card123.gif\",\"cardmode\":\"123\"}},\"2\":{\"desc\":\"电子发票\",\"code\":\"EIP\",\"page\":\"/WebAPP/pages/print/ei.html?\",\"config\":{}}}', '2021-08-09 22:23:46.000000', null, null, null, 'EIP');
INSERT INTO `ss_processconfig` VALUES ('23', 'Business', 'ED', '电子清单', '{\"1\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card123.gif\",\"cardmode\":\"123\"}},\"2\":{\"desc\":\"电子清单\",\"code\":\"ED\",\"page\":\"/WebAPP/pages/print/ed.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card12.gif\",\"cardmode\":\"12\"}}}', '2021-08-09 22:23:46.000000', null, null, null, 'ED');
INSERT INTO `ss_processconfig` VALUES ('26', 'Menu', 'Main', '主业务缴费立式', '{\"1\":{\"desc\":\"取号\",\"processcode\":\"OBTNO\",\"icons\":\"\"},\"2\":{\"desc\":\"预约\",\"processcode\":\"ORDR\",\"icons\":\"\"},\"3\":{\"desc\":\"取消预约\",\"processcode\":\"CANCORDR\",\"icons\":\"\"},\"4\":{\"desc\":\"当日挂号\",\"processcode\":\"Reg\",\"icons\":\"\"},\"5\":{\"desc\":\"门诊缴费\",\"processcode\":\"Charge\",\"icons\":\"\"},\"6\":{\"desc\":\"医生加号\",\"processcode\":\"DRINCRNO\",\"icons\":\"\"},\"7\":{\"desc\":\"凭条打印\",\"processcode\":\"CERTPRT\",\"icons\":\"\"},\"8\":{\"desc\":\"联合门诊\",\"processcode\":\"UnionOP\",\"icons\":\"\"},\"9\":{\"desc\":\"查询\",\"processcode\":\"QURY\",\"icons\":\"\"},\"10\":{\"desc\":\"健康天津\",\"processcode\":\"HLTJ\",\"icons\":\"\"}}', '2021-08-09 22:23:46.000000', null, null, null, '');
INSERT INTO `ss_processconfig` VALUES ('27', 'Menu', 'BGJ-Main', '壁挂机主业务', '{\"1\":{\"desc\":\"取号\",\"processcode\":\"OBTNO\",\"icons\":\"\"},\"2\":{\"desc\":\"预约\",\"processcode\":\"ORDR\",\"icons\":\"\"},\"3\":{\"desc\":\"预约查询\",\"processcode\":\"PreOrder\",\"icons\":\"\"},\"4\":{\"desc\":\"取消预约\",\"processcode\":\"CANCORDR\",\"icons\":\"\"},\"5\":{\"desc\":\"当日挂号\",\"processcode\":\"Reg\",\"icons\":\"\"},\"6\":{\"desc\":\"缴费\",\"processcode\":\"Charge\",\"icons\":\"\"},\"7\":{\"desc\":\"智医凭条\",\"processcode\":\"CERTPRT\",\"icons\":\"\"},\"8\":{\"desc\":\"查询\",\"processcode\":\"QURY\",\"icons\":\"\"},\"9\":{\"desc\":\"医生加号\",\"processcode\":\"DRINCRNO\",\"icons\":\"\"}}', '2021-08-09 22:23:46.000000', null, null, null, '');
INSERT INTO `ss_processconfig` VALUES ('28', 'Business', 'CANCORDR', '联合门诊-取消预约', '{\"1\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card12.gif\",\"cardmode\":\"12\"}},\"2\":{\"desc\":\"选择预约记录\",\"code\":\"getpredetails\",\"page\":\"/WebAPP/pages/prereg/predetails.html?AllowReund=Y\",\"config\":\"\"}}', null, null, null, null, 'UnionOP-CANCORDR');
INSERT INTO `ss_processconfig` VALUES ('29', 'Menu', 'HXReg-Menu', '呼吸科-挂号-菜单', '{\"1\":{\"desc\":\"当日挂号\",\"processcode\":\"HXReg\",\"icons\":\"\"},\"2\":{\"desc\":\"预约\",\"processcode\":\"ORDR\",\"icons\":\"\"},\"3\":{\"desc\":\"预约查询\",\"processcode\":\"PreOrder\",\"icons\":\"\"},\"4\":{\"desc\":\"取消预约\",\"processcode\":\"CANCORDR\",\"icons\":\"\"},\"5\":{\"desc\":\"取号\",\"processcode\":\"OBTNO\",\"icons\":\"\"},\"6\":{\"desc\":\"缴费\",\"processcode\":\"Charge\",\"icons\":\"\"},\"7\":{\"desc\":\"智医凭条\",\"processcode\":\"CERTPRT\",\"icons\":\"\"},\"8\":{\"desc\":\"查询\",\"processcode\":\"QURY\",\"icons\":\"\"},\"9\":{\"desc\":\"医生加号\",\"processcode\":\"DRINCRNO\",\"icons\":\"\"}}', null, null, null, null, '');
INSERT INTO `ss_processconfig` VALUES ('30', 'Business', 'Reg', '呼吸科-挂号', '{\"1\":{\"desc\":\"选择患者类型\",\"code\":\"pattype\",\"page\":\"/WebAPP/pages/common/readcard.html?\",\"config\":\"\"},\"2\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":\"{\\\"url\\\":\\\"\\\",\\\"cardmode\\\":\\\"\\\"}\"},\"3\":{\"desc\":\"选择医保类别\",\"code\":\"insutype\",\"page\":\"/WebAPP/pages/insu/pattype.html?\",\"config\":\"\"},\"4\":{\"desc\":\"选择慢病类型\",\"code\":\"diag\",\"page\":\"/WebAPP/pages/insu/diag.html?\",\"config\":\"\"},\"5\":{\"desc\":\"选择一级科室\",\"code\":\"level1dep\",\"page\":\"/WebAPP/pages/prereg/level1department.html?\",\"config\":\"\"},\"6\":{\"desc\":\"选择二级科室\",\"code\":\"level2dep\",\"page\":\"/WebAPP/pages/prereg/department.html?\",\"config\":\"\"},\"7\":{\"desc\":\"选择医生\",\"code\":\"predoc\",\"page\":\"/WebAPP/pages/prereg/doctor.html?\",\"config\":\"\"},\"8\":{\"desc\":\"挂号信息\",\"code\":\"showreg\",\"page\":\"/WebAPP/pages/prereg/show.html?\",\"config\":\"\"},\"9\":{\"desc\":\"支付方式选择\",\"code\":\"paymode\",\"page\":\"/WebAPP/pages/common/paymode.html?\",\"config\":\"\"},\"10\":{\"desc\":\"支付\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?\",\"config\":\"\"}}', null, null, null, null, 'HXReg');
INSERT INTO `ss_processconfig` VALUES ('31', 'Menu', 'EP', '单独缴费', '{\"1\":{\"desc\":\"缴费\",\"processcode\":\"Charge\",\"icons\":\"\"},\"2\":{\"desc\":\"查询\",\"processcode\":\"QURY\",\"icons\":\"\"},\"3\":{\"desc\":\"智医凭条\",\"processcode\":\"CERTPRT\",\"icons\":\"\"}}', null, null, null, null, '');
INSERT INTO `ss_processconfig` VALUES ('32', 'Menu', 'FROP', '发热门诊', '{\"1\":{\"desc\":\"现场挂号\",\"processcode\":\"FR-Reg\",\"icons\":\"\"},\"2\":{\"desc\":\"查询\",\"processcode\":\"QURY\",\"icons\":\"\"},\"3\":{\"desc\":\"缴费\",\"processcode\":\"Charge\",\"icons\":\"\"},\"4\":{\"desc\":\"凭条打印\",\"processcode\":\"CERTPRT\",\"icons\":\"\"}}', null, null, null, null, '');
INSERT INTO `ss_processconfig` VALUES ('33', 'Business', 'Reg', '发热-挂号', '{\"1\":{\"desc\":\"选择患者类型\",\"code\":\"pattype\",\"page\":\"/WebAPP/pages/common/readcard.html?\",\"config\":\"\"},\"2\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":\"{\\\"url\\\":\\\"\\\",\\\"cardmode\\\":\\\"\\\"}\"},\"3\":{\"desc\":\"选择医保类别\",\"code\":\"insutype\",\"page\":\"/WebAPP/pages/insu/pattype.html?\",\"config\":\"\"},\"4\":{\"desc\":\"选择慢病类型\",\"code\":\"diag\",\"page\":\"/WebAPP/pages/insu/diag.html?\",\"config\":\"\"},\"5\":{\"desc\":\"选择一级科室\",\"code\":\"level1dep\",\"page\":\"/WebAPP/pages/prereg/level1department.html?\",\"config\":\"\"},\"6\":{\"desc\":\"选择二级科室\",\"code\":\"level2dep\",\"page\":\"/WebAPP/pages/prereg/department.html?\",\"config\":\"\"},\"7\":{\"desc\":\"选择医生\",\"code\":\"predoc\",\"page\":\"/WebAPP/pages/prereg/doctor.html?\",\"config\":\"\"},\"8\":{\"desc\":\"挂号信息\",\"code\":\"showreg\",\"page\":\"/WebAPP/pages/prereg/show.html?\",\"config\":\"\"},\"9\":{\"desc\":\"支付方式选择\",\"code\":\"paymode\",\"page\":\"/WebAPP/pages/common/paymode.html?\",\"config\":\"\"},\"10\":{\"desc\":\"支付\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?\",\"config\":\"\"}}', null, null, null, null, 'FR-Reg');
INSERT INTO `ss_processconfig` VALUES ('34', 'Business', 'OBTNO', '取号', '{\"1\":{\"desc\":\"选择患者类型\",\"code\":\"pattype\",\"page\":\"/WebAPP/pages/common/readcard.html\",\"config\":\"\"},\"2\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":{\"url\":\"\",\"cardmode\":\"\"}},\"3\":{\"desc\":\"选择医保类别\",\"code\":\"insutype\",\"page\":\"/WebAPP/pages/insu/pattype.html?\",\"config\":\"\"},\"4\":{\"desc\":\"选择慢病类型\",\"code\":\"diag\",\"page\":\"/WebAPP/pages/insu/diag.html?\",\"config\":\"\"},\"5\":{\"desc\":\"选择预约记录\",\"code\":\"getpredetails\",\"page\":\"/WebAPP/pages/prereg/predetails.html?AllowReund=GET\",\"config\":\"\"},\"6\":{\"desc\":\"挂号信息\",\"code\":\"showreg\",\"page\":\"/WebAPP/pages/prereg/show.html?\",\"config\":\"\"},\"7\":{\"desc\":\"选择支付方式\",\"code\":\"paymode\",\"page\":\"/WebAPP/pages/common/paymode.html?\",\"config\":\"\"},\"8\":{\"desc\":\"扫码\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?\",\"config\":\"\"}}', null, null, null, null, 'NA-OBTNO');
INSERT INTO `ss_processconfig` VALUES ('35', 'Menu', 'BGJTJOP', '体检壁挂机主界面', '{\"1\":{\"desc\":\"取号\",\"processcode\":\"OBTNO\",\"icons\":\"\"},\"2\":{\"desc\":\"预约\",\"processcode\":\"ORDR\",\"icons\":\"\"},\"3\":{\"desc\":\"预约查询\",\"processcode\":\"PreOrder\",\"icons\":\"\"},\"4\":{\"desc\":\"取消预约\",\"processcode\":\"CANCORDR\",\"icons\":\"\"},\"5\":{\"desc\":\"当日挂号\",\"processcode\":\"TJReg\",\"icons\":\"\"},\"6\":{\"desc\":\"缴费\",\"processcode\":\"Charge\",\"icons\":\"\"},\"7\":{\"desc\":\"智医凭条\",\"processcode\":\"CERTPRT\",\"icons\":\"\"},\"8\":{\"desc\":\"查询\",\"processcode\":\"QURY\",\"icons\":\"\"},\"9\":{\"desc\":\"医生加号\",\"processcode\":\"DRINCRNO\",\"icons\":\"\"}}', '2021-08-09 22:23:46.000000', null, null, null, '');
INSERT INTO `ss_processconfig` VALUES ('36', 'Business', 'Reg', '体检壁挂机-挂号', '{\"1\":{\"desc\":\"选择患者类型\",\"code\":\"pattype\",\"page\":\"/WebAPP/pages/common/readcard.html?\",\"config\":\"\"},\"2\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":\"{\\\"url\\\":\\\"\\\",\\\"cardmode\\\":\\\"\\\"}\"},\"3\":{\"desc\":\"选择医保类别\",\"code\":\"insutype\",\"page\":\"/WebAPP/pages/insu/pattype.html?\",\"config\":\"\"},\"4\":{\"desc\":\"选择慢病类型\",\"code\":\"diag\",\"page\":\"/WebAPP/pages/insu/diag.html?\",\"config\":\"\"},\"5\":{\"desc\":\"选择一级科室\",\"code\":\"level1dep\",\"page\":\"/WebAPP/pages/prereg/level1department.html?\",\"config\":\"\"},\"6\":{\"desc\":\"选择二级科室\",\"code\":\"level2dep\",\"page\":\"/WebAPP/pages/prereg/department.html?\",\"config\":\"\"},\"7\":{\"desc\":\"选择医生\",\"code\":\"predoc\",\"page\":\"/WebAPP/pages/prereg/doctor.html?\",\"config\":\"\"},\"8\":{\"desc\":\"挂号信息\",\"code\":\"showreg\",\"page\":\"/WebAPP/pages/prereg/show.html?\",\"config\":\"\"},\"9\":{\"desc\":\"支付方式选择\",\"code\":\"paymode\",\"page\":\"/WebAPP/pages/common/paymode.html?\",\"config\":\"\"},\"10\":{\"desc\":\"支付\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?\",\"config\":\"\"}}', null, null, null, null, 'TJReg');
INSERT INTO `ss_processconfig` VALUES ('37', 'Business', 'Reg', '挂号', '{\"1\":{\"desc\":\"选择患者类型\",\"code\":\"pattype\",\"page\":\"/WebAPP/pages/common/readcard.html?\",\"config\":{}},\"2\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":\"\"},\"3\":{\"desc\":\"选择医保类别\",\"code\":\"insutype\",\"page\":\"/WebAPP/pages/insu/pattype.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card1.png\",\"cardmode\":\"1\"}},\"4\":{\"desc\":\"流调表\",\"code\":\"srvylist\",\"page\":\"/WebAPP/pages/common/srvylist.html?\",\"config\":\"\"},\"5\":{\"desc\":\"选择慢病类型\",\"code\":\"diag\",\"page\":\"/WebAPP/pages/insu/diag.html?\",\"config\":{}},\"6\":{\"desc\":\"选择二级科室\",\"code\":\"level2dep\",\"page\":\"/WebAPP/pages/prereg/department.html?\",\"config\":\"\"},\"7\":{\"desc\":\"选择医生\",\"code\":\"predoc\",\"page\":\"/WebAPP/pages/prereg/doctor.html?\",\"config\":\"\"},\"8\":{\"desc\":\"挂号信息\",\"code\":\"showreg\",\"page\":\"/WebAPP/pages/prereg/show.html?\",\"config\":\"\"},\"9\":{\"desc\":\"支付方式选择\",\"code\":\"paymode\",\"page\":\"/WebAPP/pages/common/paymode.html?\",\"config\":\"\"},\"10\":{\"desc\":\"支付\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?\",\"config\":\"\"},\"11\":{\"desc\":\"查询就诊记录\",\"BusinessType\":\"Charge\",\"code\":\"AdmList\",\"page\":\"/WebAPP/pages/charge/admlist.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card1.png\",\"cardmode\":\"1\"}},\"12\":{\"desc\":\"确认信息\",\"code\":\"chargeshow\",\"page\":\"/WebAPP/pages/charge/divide.show.html?\",\"config\":\"\"},\"13\":{\"desc\":\"支付方式选择\",\"code\":\"paymode\",\"page\":\"/WebAPP/pages/common/paymode.html?\",\"config\":\"\"},\"14\":{\"desc\":\"支付\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?paytype=Charge\",\"config\":\"\"}}', null, null, null, null, 'NAReg-Reg');
INSERT INTO `ss_processconfig` VALUES ('38', 'Menu', 'TestReg', 'TestReg', '{\"1\":{\"desc\":\"取号\",\"processcode\":\"NAReg-OBTNO\",\"icons\":\"\"},\"2\":{\"desc\":\"预约\",\"processcode\":\"ORDR\",\"icons\":\"\"},\"3\":{\"desc\":\"预约查询\",\"processcode\":\"PreOrder\",\"icons\":\"\"},\"4\":{\"desc\":\"取消预约\",\"processcode\":\"CANCORDR\",\"icons\":\"\"},\"5\":{\"desc\":\"当日挂号New\",\"processcode\":\"NAReg-RegNew\",\"icons\":\"\"},\"6\":{\"desc\":\"交押金\",\"processcode\":\"AddDeposit\",\"icons\":\"\"},\"7\":{\"desc\":\"智医凭条\",\"processcode\":\"CERTPRT\",\"icons\":\"\"},\"8\":{\"desc\":\"查询\",\"processcode\":\"QURY\",\"icons\":\"\"},\"9\":{\"desc\":\"医生加号\",\"processcode\":\"DRINCRNO\",\"icons\":\"\"}}', '2021-08-09 22:23:46.000000', null, null, null, '');
INSERT INTO `ss_processconfig` VALUES ('39', 'Business', 'OBTNO', '核酸挂号-取号', '{\"1\":{\"desc\":\"选择患者类型\",\"code\":\"pattype\",\"page\":\"/WebAPP/pages/common/readcard.html?\",\"config\":\"\"},\"2\":{\"desc\":\"读卡\",\"code\":\"readcard\",\"page\":\"/WebAPP/pages/common/readcard.show.html?\",\"config\":{\"url\":\"\",\"cardmode\":\"\"}},\"3\":{\"desc\":\"选择医保类别\",\"code\":\"insutype\",\"page\":\"/WebAPP/pages/insu/pattype.html?\",\"config\":\"\"},\"4\":{\"desc\":\"选择慢病类型\",\"code\":\"diag\",\"page\":\"/WebAPP/pages/insu/diag.html?\",\"config\":\"\"},\"5\":{\"desc\":\"选择预约记录\",\"code\":\"getpredetails\",\"page\":\"/WebAPP/pages/prereg/predetails.html?AllowReund=GET\",\"config\":\"\"},\"6\":{\"desc\":\"挂号信息\",\"code\":\"showreg\",\"page\":\"/WebAPP/pages/prereg/show.html?\",\"config\":\"\"},\"7\":{\"desc\":\"选择支付方式\",\"code\":\"paymode\",\"page\":\"/WebAPP/pages/common/paymode.html?\",\"config\":\"\"},\"8\":{\"desc\":\"扫码\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?\",\"config\":\"\"},\"9\":{\"desc\":\"查询就诊记录\",\"BusinessType\":\"Charge\",\"code\":\"AdmList\",\"page\":\"/WebAPP/pages/charge/admlist.html?\",\"config\":{\"url\":\"/WebAPP/themes/images/card1.png\",\"cardmode\":\"1\"}},\"10\":{\"desc\":\"确认信息\",\"code\":\"chargeshow\",\"page\":\"/WebAPP/pages/charge/divide.show.html?\",\"config\":\"\"},\"11\":{\"desc\":\"支付方式选择\",\"code\":\"paymode\",\"page\":\"/WebAPP/pages/common/paymode.html?\",\"config\":\"\"},\"12\":{\"desc\":\"支付\",\"code\":\"pay\",\"page\":\"/WebAPP/pages/common/pay.html?paytype=Charge\",\"config\":\"\"}}', null, null, null, null, 'NAReg-OBTNO');
